In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1,1,1],[1,2,1]])
b = np.array([[1],[2],[12]])
a@a.T

array([[3, 4],
       [4, 6]])

In [3]:
a.T@a

array([[2, 3, 2],
       [3, 5, 3],
       [2, 3, 2]])

In [4]:
a@b

array([[15],
       [17]])

In [5]:
a = np.array([[1, -5],
             [2, 1],
             [1, 1]])
b = np.array([1, 2, 2]).T

In [6]:
a.T@a

array([[ 6, -2],
       [-2, 27]])

In [7]:
np.linalg.inv(a.T@a)

array([[0.17088608, 0.01265823],
       [0.01265823, 0.03797468]])

In [8]:
a.T@b

array([ 7, -1])

In [9]:
np.dot(np.linalg.inv(np.dot(a.T, a)), np.dot(a.T, b))

array([1.1835443 , 0.05063291])

In [10]:
a = np.array([[1,2,1],[-5,1,1]])
b = np.array([[1],[2],[2]])

In [21]:
a@b

array([[ 7],
       [-1]])

In [16]:
a@a.T

array([[ 6, -2],
       [-2, 27]])

In [20]:
c = np.linalg.inv(a@a.T)

In [22]:
a = np.array([[1,-3,1,1],[2,1,2,-1]])
b = np.array([1,4,5,0]).T

In [24]:
a@a.T

array([[12,  0],
       [ 0, 10]])

In [30]:
np.linalg.inv(a@a.T)

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

In [32]:
a@b

array([-6, 16])

In [33]:
a.T@b.T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

In [45]:
c = np.linalg.inv(a@a.T)

In [46]:
d = a@b

In [47]:
c@d

array([-0.5,  1.6])

In [48]:
a.T@a

array([[ 5, -1,  5, -1],
       [-1, 10, -1, -4],
       [ 5, -1,  5, -1],
       [-1, -4, -1,  2]])