In [1]:
import numpy as np
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

In [2]:
share_living_space = apartment[1]/apartment[0]
share_living_space

0.5277310924369748

In [3]:
apartment = np.delete(apartment, [0, 1])

In [4]:
apartment = np.append(apartment, share_living_space)
apartment

array([1.90000000e+01, 2.00000000e+00, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [5]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
t[6]

31

In [6]:
a = np.array([1,2])
b = np.array([-1,-2])
a + b

array([0, 0])

In [7]:
a = np.array([120,150,90])
b = np.array([130,130,130])
c = np.array([2,3,2.5])
c* 72

array([144., 216., 180.])

In [8]:
a+b + c*72

array([394., 496., 400.])

In [9]:
150+130+216

496

In [10]:
a = np.array([3,4,5,9])
b = np.array([1,5,3,6])
c = np.array([2,3,2.5])
d = 400* b - 200* a
d

array([-200, 1200,  200,  600])

In [11]:
a = np.array([4,6,1])
np.dot(a,a)**(1/2)

7.280109889280518

In [12]:
import pandas as pd
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})
a = Hut_Paradise_DF.values

In [13]:
a

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

In [14]:
a[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [15]:
a[:,3][2]

10

In [16]:
len(a)

9

In [17]:
a[:,1] - a[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [18]:
a[:,0]*4/10

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [19]:
b= np.array([10,20,30,15,5,40,20,8,20])
(b * a[:,4]).sum()

1348

In [20]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
u@v

0

In [21]:
a = 2*v -3*w
a

array([-3, 14,  3,  4,  2])

In [22]:
u_norm = u / np.linalg.norm(u)

v_norm = v / np.linalg.norm(v)

w_norm = w / np.linalg.norm(w)

print(u_norm[2])

print(v_norm[3])

print(w_norm[0])

0.2886751345948129
0.6666666666666666
0.21320071635561041


In [23]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [24]:
Inc = np.array([Husband_Income, Wife_Income,Mother_In_Law_Income])
Inc

array([[100, 220, 140],
       [150, 200, 130],
       [ 90,  80, 100]])

In [25]:
Cons = np.array([Husband_Сonsumption,Wife_Сonsumption ,Mother_In_Law_Сonsumption])

In [26]:
Inc - Inc * 0.13

array([[ 87. , 191.4, 121.8],
       [130.5, 174. , 113.1],
       [ 78.3,  69.6,  87. ]])

In [27]:
Inc_Tax=Inc*(1-0.13)

print(Inc_Tax[:,0])

[ 87.  130.5  78.3]


In [28]:
Inc_Tax - Cons

array([[ 37. , 141.4,  61.8],
       [ 30.5,  94. , -26.9],
       [-21.7,  49.6, -53. ]])

In [29]:
Р=Inc_Tax-Cons
print(Р[:,2])

[ 61.8 -26.9 -53. ]


In [30]:
a = np.array([[1,-1,2,4,0],[8,2,0,5,3],[0,1,2,1,2]])
b = np.array([[1,0,1,0],[0,0,2,-1],[1,0,1,1,],[0,1,1,1],[1,1,0,-1]])
np.dot(a,b)

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

In [31]:
a = np.array([[2,0],[0,3]])
b = np.array([[1,1],[4,5]])
np.dot(a,b)

array([[ 2,  2],
       [12, 15]])

In [32]:
np.dot(b,a)

array([[ 2,  3],
       [ 8, 15]])

In [33]:
a = np.array([[2,-1],[-6,3]])
b = np.array([[2,5],[4,10]])
np.dot(a,b)

array([[0, 0],
       [0, 0]])

In [34]:
a = np.array([[1,1],[2,-1],[1,2]])
np.dot(a, a.T)

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

In [35]:
a = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
a@x

array([26, 30])

In [36]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [37]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
a = np.array([x,y,z])
np.dot(a, a.T)

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [38]:
a = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
b = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])


In [39]:
a

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [40]:
b

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [41]:
c = a.loc['Борис']*b.loc['Борис']

In [42]:
c.values

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [43]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [44]:
np.dot(a *b, com)

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [45]:
np.dot(a *b, (np.ones(5) - com))

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [46]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [47]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [48]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
a = np.array([v1,v2,v3,v4])
np.linalg.matrix_rank(a)

4

In [53]:
c = a@a.T
c

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [54]:
np.linalg.det(c)

3716647.9999999995

In [55]:
np.linalg.inv(c)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])